extensions:
  search_engines:
    rocket_punch: {}
    wanted: {}
  senders:
    slack: {}
    send_grid:
      sender: hr@ashe.kr

users:
  - user: Ashe
    search_engines:
      rocket_punch: {}
      wanted: {}
    senders:
      send_grid:
        recipient:
          - tech@ashe.kr
    keywords:
      - django
